# fly.toml app configuration file generated for angular-todolist-server on 2023-07-13T17:30:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "angular-todolist-server"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
