name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check files
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.file_check.outputs.deploy }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Fetch tags
        run: git fetch --tags
      
      - name: Check modified files
        id: file_check
        run: |
          TAG_NAME=fly.deployment
          git diff --name-only $TAG_NAME HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == server/* ]]; then
              echo "Detected this file as a serverside file."
              echo "deploy=true" >> $GITHUB_OUTPUT
              break
            else
              echo "This file is not a serverside file."
              echo "deploy=false" >> $GITHUB_OUTPUT
            fi
          done < files.txt
  
  deploy:
    name: Deploy app
    needs: check
    if: needs.check.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./server
        
  tag:
    name: Tag deployment
    needs: [check, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch tags
        run: git fetch --tags
      
      - name: Check tag
        id: check_tag
        run: |
          TAG_NAME=fly.deployment
          if git show-ref --tags --quiet --verify "refs/tags/$TAG_NAME"; then
            echo "Tag $TAG_NAME exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG_NAME does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Delete tag
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          git config --global user.name "Harkeerat Kanwal"
          git config --global user.email "hsk532991@gmail.com"
          
          TAG_NAME=fly.deployment
          git tag -d $TAG_NAME
          git push --delete origin $TAG_NAME
        
      - name: Add tag
        run: |
          git config --global user.name "Harkeerat Kanwal"
          git config --global user.email "hsk532991@gmail.com"
          
          git tag -a fly.deployment HEAD -m "Tagging the current Fly deployment (Automated)"
          git push origin fly.deployment
